# #------------day 5: practical use case of classes and object & self parameter
# class Person:
#     name = "nitesh"
#     domain = "data science"
#     netsalary = 600000

#     def info(self):
#         print(f"{self.name} is a {self.domain} and his salary {self.netsalary}")


# a = Person()
# a.name = "Nitesh Negi"
# a.domain = "Data Science"
# a.netsalary = 600000

# a.info()

# a=5
# print(a)
# a="nitesh"
# print(a)
# print(type(a))
# a= int(input("enter the first lemgth "))
# b= int(input("enter the  second lenght"))
# BMI = a/b
# print(BMI)

# wap to convert celcius to ferhenhite

c= int(input("Enter the celcius value: "))
f = c*9/5+32
print(f)